# -*- coding: utf-8 -*-
"""deteccao-leito-hospitalar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E4xF5iQVVFWE0ZAXDe59PQiC8BzpBxDi
"""

# Instalar as bibliotecas YOLO e Roboflow
!pip install ultralytics Roboflow

# Conectar o Colab ao Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Descompactar dataset
!unzip leito-hospitalar.v5i.yolov8.zip

# Treinar o modelo e salvar os arquivos no Google Drive
!yolo task=detect mode=train model=yolov8n.pt data=data.yaml epochs=50 imgsz=640 project="/content/drive/MyDrive/yolov8_leito_hospitalar" name="training_run_1"

# Avaliar o modelo salvo no meu drive com imagens já treinadas
!yolo task=detect mode=predict model="/content/drive/MyDrive/yolov8_leito_hospitalar/training_run_1/weights/best.pt" source="train/images"

# Descompactar teste.zip
!unzip teste.zip

# Avaliar o modelo com imagens que não foram treinadas - teste
!yolo task=detect mode=predict model="/content/drive/MyDrive/yolov8_leito_hospitalar/training_run_1/weights/best.pt" source="teste"